version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: aquaguard-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: aquaguard-frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - ./.streamlit:/app/.streamlit
